[package]
name = "fractions-rs"
version = "0.1.8"
edition = "2021"
rust-version = "1.70"
authors = ["Wai-Shing Luk"]
description = "Fractions numbers implementation for Rust"
homepage = "https://luk036.github.io/fractions-rs"
documentation = "https://docs.rs/fractions-rs"
readme = "README.md"
keywords = ["mathematics", "numerics", "fractions"]
categories = ["algorithms", "data-structures", "science", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/luk036/fractions-rs"
exclude = [
    "/bors.toml",
    "/ci/*",
    "/.github/*",
]

[lib]
name = "fractions"
path = "src/lib.rs"

[package.metadata.docs.rs]
features = ["std", "num-bigint-std", "serde"]

[features]
default = ["num-bigint-std", "std"]
num-bigint-std = ["num-bigint/std"]
std = [
    "num-integer/std",
    "num-traits/std",
    "dep:env_logger",
    "dep:log",
]

[dependencies]
num-bigint = { version = "0.4.6", optional = true, default-features = false }
num-integer = { version = "0.1.46", features = ["i128"], default-features = false }
num-traits = { version = "0.2.19", features = ["i128"], default-features = false }
serde = { version = "1.0.228", optional = true, default-features = false }
env_logger = { version = "0.11.10", optional = true }
log = { version = "0.4.32", optional = true }

[dev-dependencies]
proptest = "1"
criterion = "0.8.2"

[[bench]]
name = "fraction_benchmarks"
harness = false

[profile.release]
opt-level = 'z'     # Optimize for size. 's' is also an option.
lto = true          # Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimization opportunities
strip = "debuginfo" # Strip debug info from the binary
