[package]
name = "fractions-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fractions"
path = "src/lib.rs"

[dependencies]
num-integer = { version = "0.1.44" }
num-traits = { version = "0.2.14" }
